### ISSUE TITLE
Request to support Openshift 4.3

### ISSUE THREAD

**Issue by aneeshkp** [redhat-nfvpe/kni-upi-lab#48]
Want to use kni-upi-lab to use 4.3
Example : https://openshift-release-artifacts.svc.ci.openshift.org/4.3.0-0.ci-2019-10-08-092115

**Comment by abays** [comment]
Now available.  Set `common.sh` `OPENSHIFT_RHCOS_MAJOR_REL` to "4.3" and you're good to go.
